## importation des bibliotheques

In [7]:
import pandas as pd
import matplotlib.pyplot as ptl#visualiser les données-> les courbes

## Etape 1.Collection des données dans un seul ficher

**1.Observation du data**

In [8]:
df=pd.read_csv('/content/Sales_April_2019.csv')
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

**2.Creaton de nouveau fichier pour stokage**

In [9]:
AllFiles=pd.DataFrame()
AllFiles

Empty DataFrame
Columns: []
Index: []

**3.Lire tous les fichier et les metre dans une valeurs**

In [10]:
import os
repertoire='/content'
files=os.listdir(repertoire)

doc = [f for f in files
            if os.path.isfile(os.path.join(repertoire, f))]

for file in doc :
  print(file)

Sales_November_2019.csv
Sales_July_2019.csv
Sales_February_2019.csv
Sales_March_2019.csv
Sales_September_2019.csv
Sales_December_2019.csv
Sales_August_2019.csv
Sales_January_2019.csv
Sales_June_2019.csv
Sales_May_2019.csv
Sales_April_2019.csv
Sales_October_2019.csv

**4.Concatiner tous les fichiers dans le une seul**

In [11]:
AllFiles = pd.concat(map(pd.read_csv, doc ), ignore_index=True)
AllFiles.sample(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
184045,276117,Google Phone,1,600,10/30/19 17:28,"886 Lakeview St, Seattle, WA 98101"
152393,180678,Lightning Charging Cable,1,14.95,04/17/19 17:04,"225 Chestnut St, New York City, NY 10001"
13447,291646,USB-C Charging Cable,1,11.95,11/04/19 19:50,"680 5th St, Los Angeles, CA 90001"
132618,195193,Lightning Charging Cable,1,14.95,05/24/19 11:38,"42 Walnut St, Seattle, WA 98101"
172682,265283,Lightning Charging Cable,1,14.95,10/02/19 01:09,"227 Willow St, Los Angeles, CA 90001"
48533,166258,Apple Airpods Headphones,1,150,03/27/19 18:29,"795 Cherry St, New York City, NY 10001"
43636,161596,Flatscreen TV,1,300,02/20/19 15:10,"47 West St, San Francisco, CA 94016"
66087,254665,Wired Headphones,1,11.99,09/11/19 16:45,"818 Spruce St, New York City, NY 10001"
116591,149321,27in 4K Gaming Monitor,1,389.99,01/12/19 11:03,"842 Wilson St, San Francisco, CA 94016"
63947,252615,Lightning Charging Cable,1,14.95,09/11/19 16:08,"746 Sunset St, Atlanta, GA 30301"

**5.Exporter le DataFram**

In [12]:
AllFiles.to_csv('/content/Sales.csv', index=False)

In [13]:
product=pd.read_csv('/content/Sales.csv')
product

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,278797,Wired Headphones,1,11.99,11/21/19 09:54,"46 Park St, New York City, NY 10001"
1,278798,USB-C Charging Cable,2,11.95,11/17/19 10:03,"962 Hickory St, Austin, TX 73301"
2,278799,Apple Airpods Headphones,1,150.0,11/19/19 14:56,"464 Cherry St, Los Angeles, CA 90001"
3,278800,27in FHD Monitor,1,149.99,11/25/19 22:24,"649 10th St, Seattle, WA 98101"
4,278801,Bose SoundSport Headphones,1,99.99,11/09/19 13:56,"522 Hill St, Boston, MA 02215"
...,...,...,...,...,...,...
186845,278792,AA Batteries (4-pack),1,3.84,10/12/19 04:32,"920 Adams St, San Francisco, CA 94016"
186846,278793,Wired Headphones,1,11.99,10/28/19 22:00,"161 Chestnut St, Los Angeles, CA 90001"
186847,278794,AA Batteries (4-pack),1,3.84,10/09/19 20:58,"346 Spruce St, San Francisco, CA 94016"
186848,278795,iPhone,1,700,10/31/19 17:21,"291 Hill St, Seattle, WA 98101"
186849,278796,Wired Headphones,1,11.99,10/13/19 11:20,"547 Jefferson St, Los Angeles, CA 90001"

In [14]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186850 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 8.6+ MB

Afficher les valeur NaN

In [15]:
product[product.isna().any(axis=1)]#Afficher les valeur NaN

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
69,NaN,NaN,NaN,NaN,NaN,NaN
138,NaN,NaN,NaN,NaN,NaN,NaN
544,NaN,NaN,NaN,NaN,NaN,NaN
546,NaN,NaN,NaN,NaN,NaN,NaN
781,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
184390,NaN,NaN,NaN,NaN,NaN,NaN
184779,NaN,NaN,NaN,NaN,NaN,NaN
185239,NaN,NaN,NaN,NaN,NaN,NaN
185614,NaN,NaN,NaN,NaN,NaN,NaN
185993,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
product.isnull().any()#Les valeurs true represente l'existence de au mois une valeur NAN

Order ID            True
Product             True
Quantity Ordered    True
Price Each          True
Order Date          True
Purchase Address    True
dtype: bool

In [17]:
product.isnull().all()#Si tous les valeurs sont nan il represent True mais dans ce cas il y a des valeur nan
#et des variables donc la resultat false ce qui peut etre traduit par l'existance des valeurs nan et non-nan
#True =nan
#false=nan +non-nan
#false=non-nan

Order ID            False
Product             False
Quantity Ordered    False
Price Each          False
Order Date          False
Purchase Address    False
dtype: bool

In [18]:
N=product.isnull().sum().sum()# tous les variables Nan existants
N

3270

In [19]:
nn=product.isnull().sum()# tous les variables Nan en details ligne par ligne
nn

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [20]:
product.count()#il affiches les valeurs non monquantes/non-nan

Order ID            186305
Product             186305
Quantity Ordered    186305
Price Each          186305
Order Date          186305
Purchase Address    186305
dtype: int64

In [21]:
print(product == float('NaN'))#Elle est True si les valeurs sont float ici le type est Object(pas sure)

        Order ID  Product  Quantity Ordered  Price Each  Order Date  \
0          False    False             False       False       False
1          False    False             False       False       False
2          False    False             False       False       False
3          False    False             False       False       False
4          False    False             False       False       False
...          ...      ...               ...         ...         ...
186845     False    False             False       False       False
186846     False    False             False       False       False
186847     False    False             False       False       False
186848     False    False             False       False       False
186849     False    False             False       False       False

        Purchase Address
0                  False
1                  False
2                  False
3                  False
4                  False
...                  ...
186845             False
186846             False
186847             False
186848             False
186849             False

[186850 rows x 6 columns]

In [22]:
d=product.duplicated().sum() # number des lignes duplicés
d

1162

In [23]:
dup=(product[product.duplicated()]) # afficher les
dup.sample(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
38874,NaN,NaN,NaN,NaN,NaN,NaN
79632,NaN,NaN,NaN,NaN,NaN,NaN
125312,NaN,NaN,NaN,NaN,NaN,NaN
63827,NaN,NaN,NaN,NaN,NaN,NaN
66789,NaN,NaN,NaN,NaN,NaN,NaN
47098,NaN,NaN,NaN,NaN,NaN,NaN
38989,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
25789,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
30697,NaN,NaN,NaN,NaN,NaN,NaN
121749,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address

In [24]:
product['Order Date'].unique()

array(['11/21/19 09:54', '11/17/19 10:03', '11/19/19 14:56', ...,
       '10/09/19 20:58', '10/31/19 17:21', '10/13/19 11:20'], dtype=object)

## Etape2: Nettoyer les données

**1.Enlever les valeurs Nan**

In [25]:
df_product=product.dropna(subset=['Order ID'])
df_product

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,278797,Wired Headphones,1,11.99,11/21/19 09:54,"46 Park St, New York City, NY 10001"
1,278798,USB-C Charging Cable,2,11.95,11/17/19 10:03,"962 Hickory St, Austin, TX 73301"
2,278799,Apple Airpods Headphones,1,150.0,11/19/19 14:56,"464 Cherry St, Los Angeles, CA 90001"
3,278800,27in FHD Monitor,1,149.99,11/25/19 22:24,"649 10th St, Seattle, WA 98101"
4,278801,Bose SoundSport Headphones,1,99.99,11/09/19 13:56,"522 Hill St, Boston, MA 02215"
...,...,...,...,...,...,...
186845,278792,AA Batteries (4-pack),1,3.84,10/12/19 04:32,"920 Adams St, San Francisco, CA 94016"
186846,278793,Wired Headphones,1,11.99,10/28/19 22:00,"161 Chestnut St, Los Angeles, CA 90001"
186847,278794,AA Batteries (4-pack),1,3.84,10/09/19 20:58,"346 Spruce St, San Francisco, CA 94016"
186848,278795,iPhone,1,700,10/31/19 17:21,"291 Hill St, Seattle, WA 98101"
186849,278796,Wired Headphones,1,11.99,10/13/19 11:20,"547 Jefferson St, Los Angeles, CA 90001"

**Verification**

In [26]:
df_product.isnull().sum()# nombre des valeurs NaN = 0

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

**2.Enlever les duplication**

In [27]:
df_product.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)
# `subset=None` signifie que chaque colonne est utilisée pour déterminer si deux rangées sont différentes ; Pour modifier cela, spécifiez les colonnes sous forme de tableau
# `inplace=True` signifie que la structure des données est modifiée et que les lignes en double ont disparu
#'keep=first' lesser le 1er et enlever le 2eme ligne

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,278797,Wired Headphones,1,11.99,11/21/19 09:54,"46 Park St, New York City, NY 10001"
1,278798,USB-C Charging Cable,2,11.95,11/17/19 10:03,"962 Hickory St, Austin, TX 73301"
2,278799,Apple Airpods Headphones,1,150.0,11/19/19 14:56,"464 Cherry St, Los Angeles, CA 90001"
3,278800,27in FHD Monitor,1,149.99,11/25/19 22:24,"649 10th St, Seattle, WA 98101"
4,278801,Bose SoundSport Headphones,1,99.99,11/09/19 13:56,"522 Hill St, Boston, MA 02215"
...,...,...,...,...,...,...
186845,278792,AA Batteries (4-pack),1,3.84,10/12/19 04:32,"920 Adams St, San Francisco, CA 94016"
186846,278793,Wired Headphones,1,11.99,10/28/19 22:00,"161 Chestnut St, Los Angeles, CA 90001"
186847,278794,AA Batteries (4-pack),1,3.84,10/09/19 20:58,"346 Spruce St, San Francisco, CA 94016"
186848,278795,iPhone,1,700,10/31/19 17:21,"291 Hill St, Seattle, WA 98101"
186849,278796,Wired Headphones,1,11.99,10/13/19 11:20,"547 Jefferson St, Los Angeles, CA 90001"

verification

In [28]:
df_product.duplicated().sum()

618

**Enlever les données erronées**

In [29]:
Errones=df_product[df_product['Order ID'].str[0:2]=='Or']
Errones

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1172,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1519,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1620,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1726,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1891,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
...,...,...,...,...,...,...
184502,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
184542,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
185088,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
185359,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
186774,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address

In [30]:
df_product=df_product[df_product['Order ID'].str[0:2]!='Or']
df_product

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,278797,Wired Headphones,1,11.99,11/21/19 09:54,"46 Park St, New York City, NY 10001"
1,278798,USB-C Charging Cable,2,11.95,11/17/19 10:03,"962 Hickory St, Austin, TX 73301"
2,278799,Apple Airpods Headphones,1,150.0,11/19/19 14:56,"464 Cherry St, Los Angeles, CA 90001"
3,278800,27in FHD Monitor,1,149.99,11/25/19 22:24,"649 10th St, Seattle, WA 98101"
4,278801,Bose SoundSport Headphones,1,99.99,11/09/19 13:56,"522 Hill St, Boston, MA 02215"
...,...,...,...,...,...,...
186845,278792,AA Batteries (4-pack),1,3.84,10/12/19 04:32,"920 Adams St, San Francisco, CA 94016"
186846,278793,Wired Headphones,1,11.99,10/28/19 22:00,"161 Chestnut St, Los Angeles, CA 90001"
186847,278794,AA Batteries (4-pack),1,3.84,10/09/19 20:58,"346 Spruce St, San Francisco, CA 94016"
186848,278795,iPhone,1,700,10/31/19 17:21,"291 Hill St, Seattle, WA 98101"
186849,278796,Wired Headphones,1,11.99,10/13/19 11:20,"547 Jefferson St, Los Angeles, CA 90001"

**3.convertire l'objet en type Date**

In [31]:
df_product['Order Date']

0         11/21/19 09:54
1         11/17/19 10:03
2         11/19/19 14:56
3         11/25/19 22:24
4         11/09/19 13:56
               ...
186845    10/12/19 04:32
186846    10/28/19 22:00
186847    10/09/19 20:58
186848    10/31/19 17:21
186849    10/13/19 11:20
Name: Order Date, Length: 185950, dtype: object

In [32]:
pd.to_datetime(df_product['Order Date'] , format="ISO8601",
                                           utc=True, errors='coerce')

0        NaT
1        NaT
2        NaT
3        NaT
4        NaT
          ..
186845   NaT
186846   NaT
186847   NaT
186848   NaT
186849   NaT
Name: Order Date, Length: 185950, dtype: datetime64[ns, UTC]